# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  groups:
    github-actions:
      patterns: ["*"]
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  groups:
    react:
      patterns:
        - react
        - react-dom
        - '@types/react'
        - '@types/react-dom'
      # exclude-patterns: []
    ts-eslint:
      patterns:
        - '@typescript-eslint/*'
