compressionLevel: mixed

enableGlobalCache: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.3.1.cjs
