enableGlobalCache: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.2.2.cjs

packageExtensions:
  xo@*:
    peerDependencies:
      webpack: "*"
    peerDependenciesMeta:
      webpack:
        optional: true

logFilters:
  - pattern: "provides rollup (*) with version 3.*, which doesn't satisfy what @rollup/* request*"
    level: discard
